# NAME 
name: Push images to Dockerhub and deploy on Elastic Beanstalk 
#EVENT (when the action is triggered)
# runs when update to master branch is pushed 
on: 
  push: 
    branches: 
      -masterf 
#JOBS 
jobs: 
  build_docker_images: 
    name: build docker images 
    runs-on: [ubunutu-latest]
    steps: 
      - name: checkout 
        uses: actions/checkout@v2
        # log into Docker
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          logout: true
      - name: Build Server image
        run: docker build -t cpg3/salzbike -f
             ./Server/Dockerfile ./Server
      - name: Tag our Image
        run: docker tag cpg3/salzbike 
             cpg3/salzbike:latest
      - name: Push to dockerhub
        run: docker push cpg3/salzbike
        # Deploy the Docker container to AWS 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
         aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
         aws_secret_key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
         application_name: salzbikeeb
         environment_name: salzbikeeb-env
         version_label: " app-d5ae-230706_180201548766"
         region: eu-central-1 
